# Generated by Django 6.0.1 on 2026-05-27 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('ac_repair', 'AC Repair'), ('painter', 'Painter'), ('carpenter', 'Carpenter')], max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('town', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('avatar', models.URLField(max_length=500)),
                ('bio', models.TextField()),
                ('is_emergency_available', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('rating', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('text', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('suspicious_type', models.CharField(blank=True, max_length=50, null=True)),
                ('suspicious_reason', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Confirmed', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.worker')),
            ],
        ),
    ]
